---
title: "Beer"
author: "Bradley Robinson, William Gonzalez"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
## Introduction

## Preparing the data

```{r}
beers <- read.csv("Beers.csv")
breweries <- read.csv("Breweries.csv")
head(beers)
head(breweries)
```

### How Many Breweries?

Rank each state by how many breweries they have.

```{r}
breweries_states_count <- breweries %>%
  group_by(State) %>%
  summarise(Freq = n())
state_ordered <- breweries_states_count[order(-breweries_states_count$Freq),]
head(state_ordered, n = 10)
```


```{r}
names(breweries) <- c("Brewery_id", "Brewery_Name", "City", "State")
combined <- merge(beers, breweries, by = c("Brewery_id")) 
head(combined)
tail(combined)
```
TODO: Report number of NAs in each column
```{r}

```

```{r}
beers_summarized <- combined %>%
  group_by(State) %>%
  summarise(median_abv = median(ABV, na.rm = TRUE),
          median_ibu = median(IBU, na.rm = TRUE))
beers_summarized
```

# TODO: Which state has the max ABV? Which has the most bitter (IBU)?
```{r}

```

### ABV Summary Statistics
```{r}

```

